app:
  age_range:
  - 0
  - 100
  default_age: 25
  title: Music Preference Predictor
data:
  age_bins:
  - 0
  - 25
  - 31
  - 99
  age_labels:
  - young
  - mid
  - older
  save_uploads: true
  uploads_dir: uploads
logging:
  console: true
  file: logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
model:
  models_dir: models
  n_estimators: 263
  random_state: 42
  save_model: true
  use_saved_model: true
